/**
 * PR Creator — takes an AI-generated fix and creates a pull request.
 *
 * Flow:
 *   1. Create a new branch from the base branch
 *   2. Commit the patched files to the new branch
 *   3. Open a pull request with an AI-written description
 */

import * as core from "@actions/core";
import { GitHubClient } from "./github-client";
import type { ClassifiedAlert, AIFixResult, CreatedPR, Severity } from "./types";

export class PRCreator {
  private github: GitHubClient;
  private baseBranch: string;

  constructor(github: GitHubClient, baseBranch: string = "main") {
    this.github = github;
    this.baseBranch = baseBranch;
  }

  /**
   * Create a full pull request for an AI-generated fix.
   */
  async createFixPR(
    classified: ClassifiedAlert,
    fix: AIFixResult
  ): Promise<CreatedPR> {
    const { alert, severity, cvssScore } = classified;
    const pkg = alert.dependency.package;

    // 1. Generate branch name
    const branchName = this.buildBranchName(alert.number, pkg.name);
    core.info(`[PR] Creating branch: ${branchName}`);

    // 2. Create branch from base
    const baseSha = await this.github.getBranchSha(this.baseBranch);
    await this.github.createBranch(branchName, baseSha);

    // 3. Commit files
    const commitMessage = this.buildCommitMessage(
      pkg.name,
      fix.targetVersion,
      alert.number,
      severity
    );
    await this.github.commitFiles(branchName, fix.patches, commitMessage);
    core.info(`[PR] Committed ${fix.patches.length} file(s) to ${branchName}`);

    // 4. Build PR body
    const prTitle = this.buildPRTitle(pkg.name, fix.targetVersion, severity);
    const prBody = this.buildPRBody(classified, fix);

    // 5. Open PR
    const labels = this.buildLabels(severity);
    const pr = await this.github.createPullRequest({
      title: prTitle,
      body: prBody,
      head: branchName,
      base: this.baseBranch,
      labels,
    });

    core.info(`[PR] Created PR #${pr.number}: ${pr.html_url}`);

    return {
      number: pr.number,
      html_url: pr.html_url,
      branch: branchName,
      title: prTitle,
    };
  }

  // -----------------------------------------------------------------------
  // Helpers
  // -----------------------------------------------------------------------

  private buildBranchName(alertNumber: number, packageName: string): string {
    const safeName = packageName
      .replace(/[^a-zA-Z0-9-]/g, "-")
      .replace(/-+/g, "-")
      .toLowerCase();
    return `dep-resolver/alert-${alertNumber}-${safeName}`;
  }

  private buildCommitMessage(
    packageName: string,
    targetVersion: string,
    alertNumber: number,
    severity: Severity
  ): string {
    return (
      `fix(deps): upgrade ${packageName} to ${targetVersion}\n\n` +
      `Resolves Dependabot alert #${alertNumber} (${severity} severity).\n` +
      `\n` +
      `Generated by dep-resolver-agent (AI-assisted).`
    );
  }

  private buildPRTitle(
    packageName: string,
    targetVersion: string,
    severity: Severity
  ): string {
    const badge = severity === "low" ? "🟢" : "🟡";
    return `${badge} fix(deps): upgrade ${packageName} to ${targetVersion}`;
  }

  private buildPRBody(
    classified: ClassifiedAlert,
    fix: AIFixResult
  ): string {
    const { alert, severity, cvssScore } = classified;
    const advisory = alert.security_advisory;

    const breakingWarning = fix.isBreakingChange
      ? "\n> ⚠️ **Potential breaking change** — please review carefully.\n"
      : "";

    return `## 🤖 Automated Dependency Fix

This PR was automatically generated by **dep-resolver-agent** to resolve a Dependabot security alert.

### Vulnerability Details

| Field | Value |
|-------|-------|
| **Package** | \`${alert.dependency.package.name}\` (${alert.dependency.package.ecosystem}) |
| **Advisory** | [${advisory.ghsa_id}](https://github.com/advisories/${advisory.ghsa_id}) |
| **CVE** | ${advisory.cve_id ?? "N/A"} |
| **CVSS Score** | ${cvssScore} / 10 (**${severity.toUpperCase()}**) |
| **Vulnerable range** | \`${alert.security_vulnerability.vulnerable_version_range}\` |
| **Fixed in** | \`${fix.targetVersion}\` |
| **Manifest** | \`${alert.dependency.manifest_path}\` |

### Summary
${fix.summary}
${breakingWarning}
### Risk Assessment
${fix.riskAssessment}

### Files Changed
${fix.patches.map((p) => `- \`${p.path}\``).join("\n")}

---

<details>
<summary>ℹ️ About this PR</summary>

This PR was created by [dep-resolver-agent](https://github.com) using Claude AI.
It addresses Dependabot alert [#${alert.number}](${alert.html_url}).

**All AI-generated PRs require human review before merging.**

</details>`;
  }

  private buildLabels(severity: Severity): string[] {
    const labels = ["dep-resolver", "security", "automated"];
    if (severity === "low") labels.push("low-severity");
    if (severity === "medium") labels.push("medium-severity");
    return labels;
  }
}
